import Foundation
import Combine

// MARK: - Shared paths

enum OverridePaths {
    /// ~/.mitmmenubar
    static let dir: URL = FileManager.default
        .homeDirectoryForCurrentUser
        .appendingPathComponent(".mitmmenubar", isDirectory: true)

    /// Rules file read live by the mitmproxy addon.
    static let rules: URL = dir.appendingPathComponent("overrides.json")

    /// The mitmproxy addon script, written out at launch.
    static let script: URL = dir.appendingPathComponent("response_override.py")
}

// MARK: - Model

/// A single response-override rule. Property names are the exact keys the
/// Python addon reads from overrides.json — keep them in sync.
struct OverrideRule: Codable, Identifiable, Equatable, Hashable {
    var id: UUID
    /// Substring matched against the full request URL (e.g. "/api/users").
    var endpoint: String
    /// Optional HTTP method filter ("GET", "POST", …); nil means any method.
    var method: String?
    /// Status code returned to the client.
    var statusCode: Int
    /// Raw response body returned to the client (expected to be JSON).
    var responseBody: String
    var enabled: Bool

    init(id: UUID = UUID(),
         endpoint: String = "",
         method: String? = nil,
         statusCode: Int = 200,
         responseBody: String = "{\n  \n}",
         enabled: Bool = true) {
        self.id = id
        self.endpoint = endpoint
        self.method = method
        self.statusCode = statusCode
        self.responseBody = responseBody
        self.enabled = enabled
    }
}

private struct RulesFile: Codable {
    var rules: [OverrideRule]
}

// MARK: - Store

/// Owns the override rules, persists them to disk, and writes the addon script.
/// The mitmproxy addon re-reads overrides.json on every request (mtime-cached),
/// so edits here take effect live without restarting mitmweb.
final class OverridesStore: ObservableObject {
    @Published var rules: [OverrideRule] = []

    init() {
        bootstrap()
        load()
    }

    /// Ensure the config directory, addon script, and rules file exist.
    private func bootstrap() {
        try? FileManager.default.createDirectory(
            at: OverridePaths.dir,
            withIntermediateDirectories: true
        )

        // Always (re)write the addon so it stays in sync with this build.
        try? Self.addonScript.write(to: OverridePaths.script, atomically: true, encoding: .utf8)

        if !FileManager.default.fileExists(atPath: OverridePaths.rules.path) {
            save()
        }
    }

    func load() {
        guard let data = try? Data(contentsOf: OverridePaths.rules),
              let decoded = try? JSONDecoder().decode(RulesFile.self, from: data) else {
            return
        }
        rules = decoded.rules
    }

    /// Persist rules to disk. The addon picks up the change on its next request.
    func save() {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        guard let data = try? encoder.encode(RulesFile(rules: rules)) else { return }
        try? data.write(to: OverridePaths.rules, options: .atomic)
    }

    // MARK: - Mutations

    func addRule() -> OverrideRule {
        let rule = OverrideRule()
        rules.append(rule)
        save()
        return rule
    }

    func delete(id: UUID) {
        rules.removeAll { $0.id == id }
        save()
    }
}

// MARK: - Embedded mitmproxy addon

extension OverridesStore {
    /// Python addon loaded via `mitmweb -s`. Short-circuits matching requests in
    /// the `request` hook so the upstream server is never contacted. Reloads the
    /// rules file whenever its modification time changes.
    static let addonScript = """
    # Auto-generated by MITMMenuBar. Do not edit by hand — it is overwritten on launch.
    import json
    import os

    from mitmproxy import http

    OVERRIDES_PATH = os.path.expanduser("~/.mitmmenubar/overrides.json")

    _cache = {"mtime": None, "rules": []}


    def _load_rules():
        try:
            mtime = os.path.getmtime(OVERRIDES_PATH)
        except OSError:
            _cache["mtime"] = None
            _cache["rules"] = []
            return _cache["rules"]

        if mtime != _cache["mtime"]:
            try:
                with open(OVERRIDES_PATH, "r", encoding="utf-8") as f:
                    _cache["rules"] = json.load(f).get("rules", [])
                _cache["mtime"] = mtime
            except (OSError, ValueError):
                _cache["rules"] = []
        return _cache["rules"]


    def request(flow: http.HTTPFlow) -> None:
        url = flow.request.pretty_url
        for rule in _load_rules():
            if not rule.get("enabled", True):
                continue

            endpoint = (rule.get("endpoint") or "").strip()
            if not endpoint or endpoint not in url:
                continue

            method = rule.get("method")
            if method and method.upper() != flow.request.method.upper():
                continue

            try:
                status = int(rule.get("statusCode", 200))
            except (TypeError, ValueError):
                status = 200

            body = rule.get("responseBody") or ""
            flow.response = http.Response.make(
                status,
                body.encode("utf-8"),
                {"Content-Type": "application/json"},
            )
            return
    """
}
